version: '3.5'

services:

  zookeeper:
    image: quay.io/strimzi/kafka:0.23.0-kafka-2.8.0
    command: [
      "sh", "-c",
      "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    network_mode: "host"
    ports:
      - "2181:2181"
    environment:
      LOG_DIR: /tmp/logs
    # networks:
    #   - kafka-quickstart-network

  kafka:
    image: quay.io/strimzi/kafka:0.23.0-kafka-2.8.0
    command: [
      "sh", "-c",
      "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT} --override num.partitions=$${NUM_PARTITIONS}"
    ]
    depends_on:
      - zookeeper
    network_mode: "host"
    ports:
      - "9092:9092"
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      NUM_PARTITIONS: 3
    # networks:
    #   - kafka-quickstart-network

  # producer:
  #   image: quarkus-quickstarts/kafka-quickstart-producer:1.0-${QUARKUS_MODE:-jvm}
  #   build:
  #     context: producer
  #     dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
  #   depends_on:
  #     - kafka
  #   environment:
  #     KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - kafka-quickstart-network

  # processor:
  #   image: quarkus-quickstarts/kafka-quickstart-processor:1.0-${QUARKUS_MODE:-jvm}
  #   build:
  #     context: processor
  #     dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
  #   depends_on:
  #     - kafka
  #   environment:
  #     KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  #   networks:
  #     - kafka-quickstart-network

# networks:
#   kafka-quickstart-network:
#     name: kafkaquickstart
